GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsIm5hbWUiOiJJaHNhbnVsQWxpZjQ1IiwiZW1haWwiOiJlbWFpbDIxQGdtYWlsLmNvbSIsImlhdCI6MTY1NDEzMTQ5NywiZXhwIjoxNjU0MTMxNTI3fQ.YRDYRoNwv_MF6PLoK6K4Dy7JMf0uiaUSXo2gP5nqoKY

###
POST  http://localhost:5000/register
Content-Type: application/json

{
    "name": "IhsanulAlif45",
    "email": "email21@gmail.com",
    "password": "12345",
    "confPassword": "12345"
}

###
POST  http://localhost:5000/login
Content-Type: application/json

{
    "email":"email21@gmail.com",
    "password":"12345"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout